import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const data = api.welcome.getEventDescription.useQuery({ text: "test" });

  return (
    <>
      <Head>
        <title>YITP</title>
        {/* <meta name="description" content="Generated by create-t3-app" /> */}
        <link rel="icon" href="/YITP.ico" />
      </Head>
      <main className="flex flex-col items-center justify-center bg-gradient-to-b from-[#d5d7db] to-[#a0aec0]">
        <div className="container flex flex-grow flex-col items-center justify-center gap-12 px-4 py-16 ">
          {/* <div className="grid max-w-xs grid-cols-1 gap-4 sm:grid-cols-5 md:gap-5 "> */}
          <div className="grid grid-cols-1 place-items-center items-center gap-4 text-center sm:max-w-xs sm:grid-cols-5 sm:place-items-center sm:items-start md:gap-5">
            {/* sm:place-items-center sm:text-center */}
            {/* <div className="flex items-center"> */}
            <Link
              // className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              className="col-span-4 flex-1"
              href="https://www.linkedin.com/company/young-it-professionals/"
              target="_blank"
            >
              <h1 className=" text-5xl font-extrabold tracking-tight text-white hover:scale-105 sm:text-[4rem]">
                {/* <h1 className="flex-1 whitespace-normal text-5xl font-extrabold tracking-tight text-white hover:scale-105 sm:text-[4rem]"> */}{" "}
                {/* hover:text-6xl hover:sm:text-[5rem]*/}
                <span className="text-[hsl(300,1%,28%)]">Y</span>
                oung <span className="text-[hsl(300,1%,28%)]">IT</span>{" "}
                <span className="text-[hsl(300,1%,28%)]">P</span>
                rofessionals
              </h1>
            </Link>
            <button
              type="button"
              data-te-ripple-init
              data-te-ripple-color="light"
              className=" 2sm:place-self-center flex h-14 w-14 flex-none items-center justify-center rounded-xl bg-blue-600 text-xs text-white shadow-md hover:scale-110 hover:shadow-xl focus:shadow-lg active:shadow-lg"
              onClick={() =>
                window.open(
                  "https://www.linkedin.com/company/young-it-professionals/",
                  "_blank"
                )
              }
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="h-4 w-4"
                fill="currentColor"
                viewBox="0 0 24 24"
              >
                <path d="M4.98 3.5c0 1.381-1.11 2.5-2.48 2.5s-2.48-1.119-2.48-2.5c0-1.38 1.11-2.5 2.48-2.5s2.48 1.12 2.48 2.5zm.02 4.5h-5v16h5v-16zm7.982 0h-4.968v16h4.969v-8.399c0-4.67 6.029-5.052 6.029 0v8.399h4.988v-10.131c0-7.88-8.922-7.593-11.018-3.714v-2.155z" />
              </svg>
            </button>
          </div>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-3 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="/aboutYITP"
              // target="_blank"
            >
              <h3 className="text-2xl font-bold">YITP →</h3>
              <div className="text-lg">
                The Network for young emerging professionals working within the
                dynamic and evolving IT industry.
                {/* A network for young IT professionals with the purpose of connecting people across companies and roles. */}
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://kpmg.com/dk/en/home/services/advisory/newtech/Machine%20Learning%20&%20Quantum/quantum-tech.html"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">KPMG →</h3>
              <div className="text-lg">
                KPMG’s Global Quantum Hub located in Copenhagen. Explore the
                future of business at KPMG.
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://www.microsoft.com/da-dk/development/"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Microsoft →</h3>
              <div className="text-lg">
                Ground-breaking research in quantum computing at our advanced
                quantum research labs.
              </div>
            </Link>
          </div>

          <div className="flex max-w-screen-lg flex-col flex-wrap items-center justify-center">
            <h2 className="mb-4 text-center text-2xl font-bold text-gray-700">
              Event Agenda
            </h2>

            <div className="grid-rows grid gap-4">
              {data.data?.agenda.map((item, index) => {
                return (
                  <div
                    key={index}
                    className="rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
                  >
                    <h3 className="text-lg">{item.time}</h3>
                    <p className="text-sm">{item.description}</p>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
